### ISSUE TITLE
Application class not found after updating the version of kvs-schema

### ISSUE THREAD

**Issue by tiwanari** [rejasupotaro/kvs-schema#20]
Hi,

Thank you for this really useful library :)

Recently, I updated the version of kvs-schema and had a trouble... Please help me 😢 

# Problem
I updated the version of kvs-schema from 3.1.0 to 5.0.0 (and I also tried 4.1.0) and I got a ClassNotFoundException when I launched an application I'm working on.

The error message is like this:
```
FATAL EXCEPTION: main
Process: com.pileproject.drive.nxt, PID: 2348
java.lang.RuntimeException: Unable to instantiate application com.pileproject.drive.app.DriveApplication: java.lang.ClassNotFoundException: Didn't find class "com.pileproject.drive.app.DriveApplication" on path: DexPathList[[zip file "/data/app/com.pileproject.drive.nxt-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pileproject.drive.app.DriveApplication" on path: DexPathList[[zip file "/data/app/com.pileproject.drive.nxt-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.Instrumentation.newApplication(Instrumentation.java:980)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
	... 10 more
	Suppressed: java.lang.ClassNotFoundException: com.pileproject.drive.app.DriveApplication
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 13 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

# When it happens
1. Change build.gradle from
```
apt 'com.github.rejasupotaro.kvs-schema:compiler:3.1.0'
compile 'com.github.rejasupotaro.kvs-schema:library:3.1.0'
```
to
```
apt 'com.rejasupotaro:kvs-schema-compiler:5.0.0'
compile 'com.rejasupotaro:kvs-schema:5.0.0'
```
in order to use an upper version.
2. Modify some codes to adjust app for the changes of version up (e.g. add `name =` to Key annotation).
3. Get an error just after launching app.

# Code for reproduction
I made a branch and committed a change to reproduce the problem.
branch: https://github.com/tiwanari/drive/tree/report/application_class_not_found
change: https://github.com/tiwanari/drive/commit/13f41dca6230b05264d6b676ab4eb6bc4ce2b069

# Environment
## Devices
I just checked two devices on Genymotion 2.6.0.
- Google Nexus 7 Android 5.1.0 
- Google Nexus 6P Android 6.0.0

## Development
Android Studio 2.1

# What help I need
I just want to know the cause of the exception. I'm not sure the differences between these versions.

**Comment by rejasupotaro** [comment]
Hi @tiwanari ! Thank you for reporting.

I looked the issue and got an error when I tried to build the branch (https://github.com/tiwanari/drive/tree/report/application_class_not_found).

It seems that `CommonPreferencesSchema` should also be migrated. The build succeeded after I updated the schema class.

The diff is below.

```java
 @Table(name = "common_preferences")
 public class CommonPreferencesSchema {
-    @Key("supervisor_mode")
-    boolean supervisorMode = false;
+    @Key(name = "supervisor_mode")
+    final boolean supervisorMode = false;
 }
```

Can you try to build again with this change?

**Comment by tiwanari** [comment]
Oh, thank you for your kind reply and so sorry for that 😭 

I pushed the change to the branch (https://github.com/tiwanari/drive/tree/report/application_class_not_found).
With the change, I succeeded building the app but yet got the same exception when I launched it... I want to know if you haven't met the exception after starting the app.

Thanks

**Comment by rejasupotaro** [comment]
Okay, let me share more detail.

- Tried building using 2 PCs.
- Tried building from Android Studio and `./gradlew`.

Each build succeeded and the app launched normally.

<img src="https://cloud.githubusercontent.com/assets/883148/15115055/fe8d3c98-1637-11e6-9217-9b14b001e31a.png" width="160px">

The build environment could be a cause. Can you try a command below and let me know the output?

```java
./gradlew clean assembleNxtDebug installNxtDebug
```

**Comment by tiwanari** [comment]
Wow, it works properly with the command! 😮 
```
./gradlew clean assembleNxtDebug installNxtDebug
```

I meet the exception only when I launch the app with AndroidStudio (Run -> Run 'app'). I haven't understood yet why this happens in the situation but thank you very much for a solution to avoid the exception! 🙇

**Comment by tiwanari** [comment]
I did something and the error never occur recently...  :confused: It may be a problem related to some settings of JDK or so. Anyway, it should be a rare case because there are no reporters and please close this issue. Thanks a lot :sparkles:

**Comment by rejasupotaro** [comment]
Sure! Not at all 🍰
